project:
  title: "Seminario: Problemas Inversos Computacionales"
  type: website
  output-dir: docs
#  videos/
#    rtm_simulation.mp4
  # output-dir: docs

bibliography: references.bib
#csl: https://www.zotero.org/styles/elsevier-vancouver
csl: elsevier-harvard.csl
#csl: https://www.zotero.org/styles/elsevier-harvard
link-citations: true
execute:
  enabled: false
editor: visual

#filters:
#  - pseudocode

#pseudocode:
#  caption-prefix: "Algorithm"
#  reference-prefix: "Algorithm"
#  caption-number: false

format:
  clean-revealjs:
    css: styles.css
    self-contained: true
    emoji: true
    pointer:
      pointerSize: 18
    auto-stretch: false
    show-notes: true

    lightbox: true

revealjs-plugins:
  - pointer
